### ISSUE TITLE
Fail with accessing address 0x00

### ISSUE THREAD

**Issue by zhuguoliang** [AXLEproject/axle-zsim-nvmain#4]
I tried to run spec06 on zsim and they works just fine. But when I turn to use axle-zsim-nvmain. After running for a while the program output is as follows:

defaultMemory.channel0.FRFCFS-WQF capacity is 4096 MB.
Creating 4 command queues.
max system bytes = 1073740799
system bytes     = 1073740799
in use bytes     =   23325440
[H] Attached to global heap
spec_init
Loading Input Data
Duplicating 51763200 bytes
Duplicating 103526400 bytes
Duplicating 2662400 bytes
Input data 209715200 bytes in length
Compressing Input Data, level 5
[S 0] [1] Internal exception detected:
[S 0] [1]  Code: 1
[S 0] [1]  Address: 0x7ffff682ff81
[S 0] [1]  Description: Exception Code: ACCESS_INVALID_ADDRESS. Exception Address = 0x7ffff682ff81. Access Type: UNKNOWN. Access Address = 0x000000000
[S 0] [1]  Caused by invalid access to address 0x0
[S 0] [1] Backtrace (25/40 max frames)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/zsim.cpp:1402 / InternalExceptionHandler
[S 0] [1]  dwarf_form.c:0 / LEVEL_PINCLIENT::IEH_CALLBACKS::NotifyInternalException(unsigned int, LEVEL_BASE::EXCEPTION_INFO*, LEVEL_VM::CONTEXT*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL19InternalHandlerSyncEiPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTEPPKNS_14SCT_ATTRIBUTESEPNS_5PCTXTEPj+0x462) [0x3077f3b2]
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL20HandlePhysicalSignalEPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTE+0x200) [0x30785040]
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(_ZN5PINVM28SIGNAL_DETAILS_LINUX_INTEL6415InternalHandlerEiPN7BARECRT8SIGXINFOEPv+0x9a) [0x3082696a]
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(BARECRT_SigReturnRt+0) [0x30851d7c]
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/timing_event.h:173 / TimingEvent::release()
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain_mem_ctrl.cpp:439 / NVMainMemory::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/NVMObject.cpp:206 / NVM::NVMObject_hook::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/NVM/nvmain.cpp:495 / NVM::NVMain::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/NVMObject.cpp:206 / NVM::NVMObject_hook::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/MemoryController.cpp:351 / NVM::MemoryController::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/MemControl/FRFCFS-WQF/FRFCFS-WQF.cpp:331 / NVM::FRFCFS_WQF::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/NVMObject.cpp:206 / NVM::NVMObject_hook::RequestComplete(NVM::NVMainRequest*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/EventQueue.cpp:384 / NVM::EventQueue::Process()
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/EventQueue.cpp:338 / NVM::EventQueue::Loop(unsigned long)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain/src/EventQueue.cpp:525 / NVM::GlobalEventQueue::Cycle(unsigned long)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain_mem_ctrl.cpp:280 / NVMainMemory::tick(unsigned long)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/nvmain_mem_ctrl.cpp:96 / SchedEventNVMain::simulate(unsigned long)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/timing_event.h:163 / TimingEvent::run(unsigned long)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/contention_sim.cpp:309 / ContentionSim::simulatePhaseThread(unsigned int)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/contention_sim.cpp:282 / ContentionSim::simThreadLoop(unsigned int)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/build/debug/contention_sim.cpp:59 / ContentionSim::SimThreadTrampoline(void*)
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(_ZN8LEVEL_VM17VM_THREAD_DB_UNIX13THREAD_RUNNER9RunThreadEPN11OS_SERVICES7ITHREADE+0x291) [0x30790671]
[S 0] [1]  /home/zhuguoliang/project/git_proj/axle-zsim-nvmain/pin_kit/intel64/bin/pinbin(_ZN11OS_SERVICES6THREAD12RootFunctionEPv+0x26) [0x30851376]
C:Tool (or Pin) caused signal 11 at PC 0x7ffff682ff81
[H] Child 4475 done
[H] Panic on build/debug/zsim_harness.cpp:123: Child 4475 (idx 0) exit was anomalous, killing simulation

It seems that our simulator has accessed some address with null pointer. How can I find where it is?
Can anybody give me a heads up?

**Comment by hftsin** [comment]
I have the same problems. Specially, it worked well with the dram-nvmain.config file while failed with the pcm-nvmain.config.

**Comment by zhuguoliang** [comment]
I will let you know if I figured out what happens

**Comment by miconof** [comment]
The default memory controller in the pcm config was FRFCFS-WQF, which only works properly using traces. I changed it to FRFCFS which should always be the default. Pull the latest change and this should be fixed.

I've executed a couple of SPEC06 benchmarks to completion without issues.

**Comment by zhuguoliang** [comment]
Thanks!
